### ISSUE TITLE
squareBrackets Function Missing Use Case

### ISSUE THREAD

**Issue by brichard1638** [dusadrian/admisc#2]
First, thank you for providing a wonderful R package in admisc. I have enjoyed using this package. However, recently I discovered a missing use case in the squareBrackets function. It appears that when either double bracket or single bracket characters surrounds content encoded with quotation marks, the results are not correctly returned.

While I have not tested for it, I suspect this issue may also apply to the other (4) bracket-based functions provided in the admisc pkg.

I have provided a reproduction of this error for your review and consideration:

x = "tr = testroc[['rocs']]"
y = "sapply(2:length(tr),function(i) lines.roc(tr[[i]],col=i))"
squareBrackets(x)
squareBrackets(y)

The function works as expected for y but not for x. The results are as follows:

> squareBrackets(x)
character(0)
> squareBrackets(y)
[1] "i"

**Comment by dusadrian** [comment]
Hello @brichard1638,

The function was not exactly intended for all purpose use, in your example having both alphanumeric characters and punctuation inside the brackets.

But I've introduced an additional argument "regexp" which allows you to have custom regular expressions for any conceivable purpose.

This particular example is solved by:

```
squareBrackets(x, regexp = "\\[[[:alnum:]|[:punct:]]+\\]")
[1] "'rocs'"
```

This new development version can be installed via:

```
remotes::install_github("dusadrian/admisc")
```

Hope this helps,
Adrian
